# Generated by Django 5.0.7 on 2024-08-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='codigo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
