# Generated by Django 5.0.7 on 2024-08-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_entidad_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='numero_reclamos',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
