# Generated by Django 5.0.7 on 2024-08-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_entidad_numero_reclamos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='numero_reclamos',
            field=models.IntegerField(null=True),
        ),
    ]
