# Generated by Django 4.1.1 on 2024-07-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0003_delete_entidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidadreclamo',
            old_name='correo_presentao',
            new_name='celular_presenta',
        ),
        migrations.RenameField(
            model_name='entidadreclamo',
            old_name='direccion_presenta',
            new_name='correo_presenta',
        ),
        migrations.RenameField(
            model_name='entidadreclamo',
            old_name='telefono_presenta',
            new_name='domicilio_presenta',
        ),
    ]
