# Generated by Django 4.1.1 on 2024-07-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0004_rename_correo_presentao_entidadreclamo_celular_presenta_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entidadreclamo',
            table='reclamo_entidadreclamo_prueba',
        ),
    ]
