# Generated by Django 4.1.1 on 2024-07-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0005_alter_entidadreclamo_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidadreclamo',
            old_name='numero_documento_ususario',
            new_name='numero_documento_usuario',
        ),
        migrations.RenameField(
            model_name='entidadreclamo',
            old_name='tipo_documento_ususario',
            new_name='tipo_documento_usuario',
        ),
    ]
