# Generated by Django 4.1.1 on 2024-07-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0006_rename_numero_documento_ususario_entidadreclamo_numero_documento_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entidadreclamo',
            table='reclamo_entidadreclamo',
        ),
    ]
