# Generated by Django 4.1.1 on 2024-07-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0007_alter_entidadreclamo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entidadreclamo',
            table='reclamo_entidadreclamo_prueba',
        ),
    ]
