# Generated by Django 4.1.1 on 2024-07-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0008_alter_entidadreclamo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadreclamo',
            name='fecha_reclamo',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
