# Generated by Django 5.0.7 on 2024-07-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0009_entidadreclamo_fecha_reclamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadreclamo',
            name='codigo_registro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
