# Generated by Django 5.0.7 on 2024-07-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0010_entidadreclamo_codigo_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='codigo_registro',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
