# Generated by Django 5.0.7 on 2024-07-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0011_alter_entidadreclamo_codigo_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='codigo_registro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
