# Generated by Django 5.0.7 on 2024-07-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0017_remove_entidadreclamo_codigo_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadreclamo',
            name='codigo_registro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
