# Generated by Django 5.0.7 on 2024-07-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0020_entidadreclamo_codigo_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='codigo_registro',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
