# Generated by Django 5.0.7 on 2024-08-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0022_remove_entidadreclamo_codigo_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadreclamo',
            name='codigo_registro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
