# Generated by Django 5.0.7 on 2024-08-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0025_alter_entidadreclamo_codigo_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidadreclamo',
            name='fecha_reclamo',
        ),
    ]
